/**
 * pnpm strips:gen — regenerate src/config/strips.ts from scripts/strip-recipe.ts.
 * Deterministic: same recipe → same file.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { SYMBOLS } from '../src/config/symbols';
import { buildStripSet } from './lib/strip-builder';
import { BASE_RECIPE, FREE_RECIPE } from './strip-recipe';

const symbols = SYMBOLS;
const base = buildStripSet(BASE_RECIPE, symbols);
const free = buildStripSet(FREE_RECIPE, symbols);

const fmt = (set: number[][]): string =>
  set.map((s) => `    [${s.join(', ')}],`).join('\n');

const legend = Object.entries(symbols)
  .map(([id, d]) => `${d.code}=${id}`)
  .join('  ');

const out = `/* GENERATED by \`pnpm strips:gen\` from scripts/strip-recipe.ts — do not edit by hand.
 * Codes: ${legend}
 * base seed: ${BASE_RECIPE.seed}   free seed: ${FREE_RECIPE.seed}
 */
import type { SymbolCode } from '@math/types';

export const BASE_STRIPS: readonly (readonly SymbolCode[])[] = [
${fmt(base)}
];

export const FREE_STRIPS: readonly (readonly SymbolCode[])[] = [
${fmt(free)}
];
`;

const target = resolve(process.cwd(), 'src/config/strips.ts');
writeFileSync(target, out);
console.log(`wrote ${target}`);
console.log(`base lengths: ${base.map((s) => s.length).join(', ')}`);
console.log(`free lengths: ${free.map((s) => s.length).join(', ')}`);
